# docker-compose.yml
version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=fact
      - MYSQL_USER=fact
      - MYSQL_PASSWORD=fact
    ports:
      - "3309:3306"
  nginx:
    image: nginx:latest
    volumes:
      - .:/data
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    ports:
      - "8009:80"
  php:
    build: ./docker/php/
    working_dir: /data
    volumes:
      - .:/data
    links:
      - mysql
